### ISSUE TITLE
specify data types

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#1]

**Comment by ahwagner** [comment]
Decide on types of data we wish to capture in meta-kb.

Information types of potential interest:
* Somatic variant interpretations
* Germline variant interpretations
* Oncogenicity / biological annotations
* Clinical trials

**Comment by ahwagner** [comment]
Discuss whether any/all association data types should be evaluated similarly (one table) or discretely (multiple tables)

Preliminary thoughts:
Interpretations (somatic and germline) are treated similarly, with field designating variant origin. Other annotations (oncogenic / functional / biological) are evaluated similarly, but distinct from interpretations. Clinical trials are independent of any other associations.

**Comment by ahwagner** [comment]
Elements we want to consider:
* Genomic features <- another issue describing what a genomic feature is (complex genotype, etc)
* Phenotypes / Disease
* Evidence
* Treatment / Therapy

**Comment by ahwagner** [comment]
Dmitri Sonkin mentioned that there is expected to be extensive overlap between germline interpretations and biological / functional annotations

**Comment by ahwagner** [comment]
As reference to the above, potential integration guidelines between somatic / germline variants are proposed by Dmitriy in this slide deck.

[somatic_germline_VICC_1a.pptx](https://github.com/cancervariants/metakb/files/2673167/somatic_germline_VICC_1a.pptx)

**Comment by bwalsh** [comment]
@ahwagner  - regarding the allele model, should we consider the meta defined by http://myvariant.info/  ? I believe there is already some collaboration with civic.  See details http://myvariant.info/metadata http://myvariant.info/metadata/fields

**Comment by ahwagner** [comment]
@bwalsh I love the idea of replicating the metadata endpoint seen at myvariant.info. With respect to metadata on fields, I think we should also consider the JSON-LD standard, which has been strongly recommended by the GA4GH GKS workstream and is highly relevant to ontology-driven works.
