### ISSUE TITLE
Resolve breaking normalizer API changes

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#152]
Catching up with:

https://github.com/cancervariants/therapy-normalization/pull/249

https://github.com/cancervariants/disease-normalization/pull/70

**Comment by korikuzma** [comment]
@jsstevenson do you want to handle this in #142

**Comment by jsstevenson** [comment]
Nah I think it's best to give it a separate branch for the sake of commit tree cleanliness

**Comment by korikuzma** [comment]
Haha okay, I would also update variation norm + pyscopg2-binary changes from [this](https://github.com/cancervariants/variation-normalization/pulls?q=is%3Apr+is%3Aclosed) PR.

**Comment by jsstevenson** [comment]
BTW I lied and committed git crimes this is gonna be in #142

**Comment by jsstevenson** [comment]
Fixed in #142
