### ISSUE TITLE
Error loading json files using --load_target_cdm

### ISSUE THREAD

**Issue by wx115** [cancervariants/metakb#164]
I downloaded json files from https://s3-us-west-2.amazonaws.com/g2p-0.10/index.html (as in the Nat Genetics paper) and tried 
"python -m metakb.cli --db_url=bolt://localhost:7687 --db_username=neo4j --db_password=admin --load_target_cdm ../download/all.json"
and get error message:
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 6518)
I tried other json files and get the same error (only the number in the brackets differ). 
Did I miss anything?

**Comment by wx115** [comment]
Tried --load_latest_cdms and get this error:
FileNotFoundError: No valid transform file found matching pattern: civic_cdm_*.json

**Comment by korikuzma** [comment]
@wx115 Ugh my bad. I gave you the wrong argument, `--load_latest_s3_cdms`

**Comment by jsstevenson** [comment]
We've altered the CLI and I think this should be working now. Please feel free to reopen or make a new issue if necessary.
