### ISSUE TITLE
Manuscript Revisions

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#22]
Revise the manuscript based off of reviewer commentary:

https://docs.google.com/document/d/1pxfGFhHK8DUu9hPhHbWqk3DsDRCorYb-jtDXfVdZ-Fg/edit?usp=sharing

**Comment by bwalsh** [comment]
See comment [here](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/125#issuecomment-459577191)
