### ISSUE TITLE
make result summary clinically focused

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#24]
>It would be much more useful for laboratory scientists trying to prepare a report for the treating oncologist, based on the variation identified (in the germline or somatic context) in the presenting patient, to have a generic description for each gene-disease-drug relationship that underscores if the drug relationship for that cancer type is relevant to only one or a limited number of variants, or variants of a given type. While the collation of data has been an impressive effort, this additional level of combined curation is what is needed to make this paper truly remarkable. Creating a summary that allows someone to type in BRAF + breast cancer and know which variants or variant types are relevant for treatment of a breast cancer patient with what drugs. There are 1274 “counts” from such a search, and at least at first glance they do not appear to be relevant to treatment of a breast cancer patient.

**Comment by ahwagner** [comment]
**Initial comments**:
_Adam Margolin_:
>This is also a pretty easy one, especially since he says it would make the paper remarkable and we should be able to do what he asks. I think what he basically needs is better documentation and ease of use of the resource. I actually can’t recapitulate the example he gives above so I don’t know how he’s doing it. When I type “braf AND breast cancer” into the search box -- https://search.cancervariants.org/#braf%20AND%20breast%20cancer -- I get 7 associations, which seems to be what he wants. The more accurate way to do this would be through the filters, but I realize these aren’t so easy to use by working through his example. A few reasons are:
>1) We kept the wonky technical names from our database as the terms to filter on and the terms displayed in the data table -- i.e. genes.keyword, association.phenotypes.term.keyword, etc. The way it’s presented in the heatmap summaries are how users would want to search and see the information displayed in the table -- i.e. categories just called “gene” or “disease”. We should think about if there’s a way to make the kind of search he’s asking for more intuitive.
>2) The operators in the filtered search only limit to “is”, “is not”, etc. So when searching for genes.keyword that are BRAF, this excludes results that have, e.g. BRAF, KRAS, and similar for searching on cancer type (“association.phenotypes.term.keyword” -- urg). So I couldn’t get the 7 results that showed up after the free text search to show up in the filter search. I think there are ways to do this more flexibly with the query language in the search bar but I don’t remember how, so it clearly wouldn’t be easy for a user to figure out. 
>
>I think at minimum we need someplace clearly referenced with better documentation on how to perform the types of searchers a user would want, such as the one suggested by the reviewer. We should give them a few example queries to run along the lines of what a user would want to do. We actually give a relatively clear example along these lines in the figure, so maybe just figure out how 

_Anonymous_:
>Should definitely address this as I think that will give us brownie points and have the reviewer firmly on our side

_Dmitriy Sonkin_:
>BRAF mutations in breast cancer are very rare. (Also vast majority of clinical and preclinical data is limited to V600 AA.) We will need to be careful with addressing this part of question.

**Comment by bwalsh** [comment]
Changes for review [here](https://github.com/ohsu-comp-bio/g2p-aggregator/issues/125#issuecomment-459577191)

**Comment by ahwagner** [comment]
👍
