### ISSUE TITLE
Consider removing analysis directory

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#248]
I never look at these (they're also not updated) and I'm not sure if other people find these useful... I think it may be more useful to create RTD

**Comment by korikuzma** [comment]
> For projects that will (eventually) have associated manuscripts, maybe we make a separate manuscript repo and put them there?

Yes, that's what we did for the variation normalizer analysis manuscript

**Comment by jsstevenson** [comment]
Should also remove the `ipykernel` dependency (imo should remove it regardless)

**Comment by korikuzma** [comment]
This was done in #320
