### ISSUE TITLE
revise documentation

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#25]
make clear, navigable documentation at docs.cancervariants.org detailing how to use the current metakb.

**Comment by bwalsh** [comment]
for reference https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-query-string-query.html#query-string-syntax

**Comment by ahwagner** [comment]
@obigriffith @malachig could I have one of you review the documentation at docs.cancervariants.org and just give a quick 👍 or suggested revisions here?
