### ISSUE TITLE
Neo4J Driver DeprecationWarning

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#278]
Seeing this warning when running tests, we should resolve

```
neo4j/_sync/driver.py:487: DeprecationWarning: Relying on Driver's destructor to close the session is deprecated. Please make sure to close the session. Use it as a context (`with` statement) or make sure to call `.close()` explicitly. Future versions of the driver will not close drivers automatically.
    deprecation_warn(
```

**Comment by jsstevenson** [comment]
see also https://neo4j.com/docs/python-manual/current/query-simple/

**Comment by jsstevenson** [comment]
Generally:

* For DB lookups, we should be using the new `execute_query` method
* For data loading, it *might* still make sense to use the session API -- I'm guessing that makes it more transactional (although I'm not sure we're using it that way right now). In that case, we need to make sure to explicitly close the session and driver:
  * in the FastAPI cleanup callback (maybe)
  * in the pytest fixture (e.g. after a yield)
  * in the data loading methods
