### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#285]
@korikuzma, didn't see an existing issue for this, apologies if I missed it

A lot of this code is from pretty far back in the day, and the type checker is flagging a lot of inconsistencies/missing annotations. It'd be good to get this fixed where possible.

In #284 I just totally removed checking annotation rules because it should probably be done separately. Once finished, that checker should go back on.

**Comment by korikuzma** [comment]
@jsstevenson I tried to add type annotations to the files I changed in my 2-alpha update work (looking at branch `issue-238`), so hopefully there won't be too many occurrences. CLI type annotations will be resolved in #244 . I think the normalizers module needs to be updated to include type annotations.
