### ISSUE TITLE
Move `variant.definingContext.expressions` to `variant.members`

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#309]
After initial talk with @ahwagner , I should move `variant.definingContext.expressions` into `variant.members`. For CIViC variants, the genomic hgvs expression should already be there. 

![Screenshot 2024-01-08 at 10 03 41 AM](https://github.com/cancervariants/metakb/assets/42851808/a06d03fb-9c09-42a0-8eae-78821d902864)

_Originally posted by @korikuzma in https://github.com/cancervariants/metakb/issues/279#issuecomment-1881497408_

**Comment by korikuzma** [comment]
@DanielPuthawala @ahwagner @larrybabb
[Here](https://github.com/user-attachments/files/16909754/civic-psc-example.json) is the current example I have. For each `expression` in `definingContext.expressions` (currently only using HGVS expressions), we try to create a VRS variation object. If successful, we add the VRS variation object to the `members` field. My questions are:

1. Do we need to have `members.expressions` populated?
  a. If so, do we use all `expressions` from the `definingContext.expressions`? If not, do we just use the `label` (which is always an HGVS expression) to create an `expression`? Do we do something else?
2. When creating normalized VRS variation objects, if multiple expressions return the same VRS object would we just create a single member with no label and expressions would be the HGVS expressions used to generate the VRS object?

**Comment by DanielPuthawala** [comment]
Forgive me Kori, but can you bring me up to speed with some context here?  Is this a question about how we interface between VRS and Cat-VRS in the context of metaKB entries?

**Comment by korikuzma** [comment]
@DanielPuthawala Yes

**Comment by korikuzma** [comment]
@DanielPuthawala I will be working on updating the CIViC + MOA CDMs (which leverage VRS/Cat-VRS/VA-Spec) for plenary. There is [this](https://github.com/ga4gh/cat-vrs/blob/1.x/examples/proteinSequenceConsequence-ex1.yaml) example in cat-vrs, but it doesn't quite show what I need to do for members/expressions.

**Comment by ahwagner** [comment]
> [Here](https://github.com/user-attachments/files/16909754/civic-psc-example.json) is the current example I have. For each `expression` in `definingContext.expressions` (currently only using HGVS expressions), we try to create a VRS variation object. If successful, we add the VRS variation object to the `members` field. My questions are:
> 
> 1. Do we need to have `members.expressions` populated?
It isn't a requirement, but I think would be more informative than using the label field. I recommend we do so.

>    a. If so, do we use all `expressions` from the `definingContext.expressions`?
I'm not sure I understand this. The defining context is one variant with one expression; the members associated with the categorical variant are each different variants from the defining context, and each should have one HGVS expression.

> 2. When creating normalized VRS variation objects, if multiple expressions return the same VRS object would we just create a single member with no label and expressions would be the HGVS expressions used to generate the VRS object?
To answer this, would you clarify what you mean when by "normalized VRS variation objects"? Does this mean VRS normalization (VOCA)? Or does this mean with the liftover and transcript selection methods we implemented in the Variation Normalization service?

**Comment by korikuzma** [comment]
Another question.... In my example, there is a `member` that has the same VRS variation as the `definingContext`. Does this make sense? Should we have the protein variant be the `definingContext` and not a `member`?

**Comment by korikuzma** [comment]
> > [Here](https://github.com/user-attachments/files/16909754/civic-psc-example.json) is the current example I have. For each `expression` in `definingContext.expressions` (currently only using HGVS expressions), we try to create a VRS variation object. If successful, we add the VRS variation object to the `members` field. My questions are:
> > 
> > 1. Do we need to have `members.expressions` populated?
> 
> It isn't a requirement, but I think would be more informative than using the label field. I recommend we do so.

🫡 
> 
> > a. If so, do we use all `expressions` from the `definingContext.expressions`?
> 
> I'm not sure I understand this. The defining context is one variant with one expression; the members associated with the categorical variant are each different variants from the defining context, and each should have one HGVS expression.

That answers my question!

> > 2. When creating normalized VRS variation objects, if multiple expressions return the same VRS object would we just create a single member with no label and expressions would be the HGVS expressions used to generate the VRS object?
> 
> To answer this, would you clarify what you mean when by "normalized VRS variation objects"? Does this mean VRS normalization (VOCA)? Or does this mean with the liftover and transcript selection methods we implemented in the Variation Normalization service?

Both -- VOCA + liftover/transcript selection

**Comment by DanielPuthawala** [comment]
That is the case because the catvar is specified at the protein level in this case, so you can end up with a synonymous assayed protein variant as the catvar.  But any assayed nucleotide variants couldn't end up with synonymous hashes, and so would only show up in members.

So it's possible for an assayed and categorical variant to share the same ID, but isn't necessarily meaningful, just indicative of synonymy.  Assayed variants show up in `members`.

**Comment by korikuzma** [comment]
> I'm not sure I understand this. The defining context is one variant with one expression;

@ahwagner Wait, how would we handle [this](https://civicdb.org/variants/4023/summary) variant? `NP_000133.1:p.Ala391Glu` and `ENSP00000414914.2:p.Ala391Glu` are provided and return the same VRS computed identifier. Wouldn't we want to store both expressions?

**Comment by DanielPuthawala** [comment]
I think those should be different relations, right @ahwagner?

**Comment by korikuzma** [comment]
> I think those should be different `relations`, right @ahwagner? Because they the same variant just represented in different systems.

@DanielPuthawala when you say 'relations', are you talking about mappings?

**Comment by korikuzma** [comment]
This example in cat-vrs also has multiple expressions for a definingContext: https://github.com/ga4gh/cat-vrs/blob/1.x/examples/canonicalAllele-ex1.yaml#L30-L36

**Comment by DanielPuthawala** [comment]
No,  At least in Cat-VRS, `relations` and `mappings` are performing different functions.  A `relation` points to equivalent representations in the system, such as HGVS vs SPDI, or on liftover between GRCh 37 to 38.  On the other hand, `mappings`  point to equivalent entries between systems, like the same thing in CIViC, ClinVar, and MOA.

**Comment by DanielPuthawala** [comment]
> This example in cat-vrs also has multiple expressions for a definingContext: https://github.com/ga4gh/cat-vrs/blob/1.x/examples/canonicalAllele-ex1.yaml#L30-L36

Oh...  I think these are from the VRSatile times.  I need to update them.

**Comment by ahwagner** [comment]
From https://github.com/cancervariants/metakb/issues/309#issuecomment-2334307476: 
> Both -- VOCA + liftover/transcript selection. We use Variation Normalizer to normalize expressions

Okay. I think we should discuss what this looks like in MetaKB. Don't have time to diagram now but will follow-up on this as a separate thread.

From https://github.com/cancervariants/metakb/issues/309#issuecomment-2334330355:

> > I'm not sure I understand this. The defining context is one variant with one expression;
> 
> @ahwagner Wait, how would we handle [this](https://civicdb.org/variants/4023/summary) variant? `NP_000133.1:p.Ala391Glu` and `ENSP00000414914.2:p.Ala391Glu` are provided and return the same VRS computed identifier. Wouldn't we want to store both expressions?

Hey, yes, you're right. Wasn't thinking about RefSeq/Ensembl when I said they should each of have one HGVS expression. Yes, these could both be valid expressions, and we should support both if easy to do. But if not easy (e.g. requiring extensive work in UTA or SeqRepo), just start with RefSeq. 

Regarding other, non-HGVS types, if it is quick to add support for SPDI (should be simple) and/or gnomAD (slightly more complicated) expression types, that is good. But not required.

From https://github.com/cancervariants/metakb/issues/309#issuecomment-2334358295 and related: 

For `relations` vs. `mappings`, I usually speak about these terms in the context of the SKOS standard definitions. Yes, [relations](https://www.w3.org/TR/skos-reference/#semantic-relations) are the semantic relationships between concepts within a vocabulary, and [mappings](https://www.w3.org/TR/skos-reference/#mapping) are the relationships between concepts across vocabularies. I don't think either apply with respect to this particular issue; the various expressions for a given contextual variant are simply part of an `expressions` array. I expect we will have concept relations inheriting from SKOS relations in MetaKB; to follow on another issue.

**Comment by korikuzma** [comment]
> From [#309 (comment)](https://github.com/cancervariants/metakb/issues/309#issuecomment-2334307476):
> 
> > Both -- VOCA + liftover/transcript selection. We use Variation Normalizer to normalize expressions
> 
> Okay. I think we should discuss what this looks like in MetaKB. Don't have time to diagram now but will follow-up on this as a separate thread.

👍 

> From [#309 (comment)](https://github.com/cancervariants/metakb/issues/309#issuecomment-2334330355):
> 
> > > I'm not sure I understand this. The defining context is one variant with one expression;
> > 
> > 
> > @ahwagner Wait, how would we handle [this](https://civicdb.org/variants/4023/summary) variant? `NP_000133.1:p.Ala391Glu` and `ENSP00000414914.2:p.Ala391Glu` are provided and return the same VRS computed identifier. Wouldn't we want to store both expressions?
> 
> Hey, yes, you're right. Wasn't thinking about RefSeq/Ensembl when I said they should each of have one HGVS expression. Yes, these could both be valid expressions, and we should support both if easy to do. But if not easy (e.g. requiring extensive work in UTA or SeqRepo), just start with RefSeq.
> 
> Regarding other, non-HGVS types, if it is quick to add support for SPDI (should be simple) and/or gnomAD (slightly more complicated) expression types, that is good. But not required.

@ahwagner we are pulling this information (HGVS expressions) directly from CIViC `HGVS Descriptions`. I'll save creating gnomAD/SPDI expressions from the `Representative Variant Coordinates` for a future issue.

> From [#309 (comment)](https://github.com/cancervariants/metakb/issues/309#issuecomment-2334358295) and related:
> 
> For `relations` vs. `mappings`, I usually speak about these terms in the context of the SKOS standard definitions. Yes, [relations](https://www.w3.org/TR/skos-reference/#semantic-relations) are the semantic relationships between concepts within a vocabulary, and [mappings](https://www.w3.org/TR/skos-reference/#mapping) are the relationships between concepts across vocabularies. I don't think either apply with respect to this particular issue; the various expressions for a given contextual variant are simply part of an `expressions` array. I expect we will have concept relations inheriting from SKOS relations in MetaKB; to follow on another issue.

👍

**Comment by korikuzma** [comment]
This is also being addressed in #388
