### ISSUE TITLE
Tweak Python version distributions on install check action

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#314]
We currently have an action that checks whether the Pipfile installs correctly, since that's what beanstalk uses. However, we run this check on 3.8-3.12, even though Beanstalk presumably only runs on a specific version. 

Maybe it would make more sense to have actions that check pip/setuptools based installation across every version (since this is how we recommend non-devs install it) and then a separate action focused specifically on Pipenv and the Python version used on elastic beanstalk.

**Comment by korikuzma** [comment]
@jsstevenson I like that. Elastic Beanstalk currently uses 3.11 for MetaKB

**Comment by korikuzma** [comment]
This was done in #316
