### ISSUE TITLE
Remove unused files/code

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#315]
.travis.yaml and probably other things

**Comment by jsstevenson** [comment]
I am fairly certain that `cron.yaml` does nothing for us on elastic beanstalk and may in fact be raising periodic errors given that we have nothing named "task1" at "/scheduled"

**Comment by korikuzma** [comment]
@jsstevenson lol maybe this is leftover from the sample app

**Comment by korikuzma** [comment]
Done in #321
