### ISSUE TITLE
Work out intersection vs union issues in `_get_related_studies` query

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#360]
- [ ] Is the intention to get all studies that incorporate _any_ of the queried terms, or _all_ of them? I think the latter, but make method name and docstring clearer.
- [ ] Fix behavior when searching for a therapy and other kinds of terms: currently, the `s1 AS s` clause seems to shadow the previously-defined studies earlier in the query, so the disease and variation clauses are ignored. See, for example, the differences between these two queries:

```cql
MATCH (s) -[:HAS_VARIANT] -> (cv:CategoricalVariation)
MATCH (cv) -[:HAS_DEFINING_CONTEXT|HAS_MEMBERS] -> (v:Variation {id:"ga4gh:VA._8jTS8nAvWwPZGOadQuD1o-tbbTQ5g3H"})
MATCH (s) -[:HAS_TUMOR_TYPE] -> (c:Condition {disease_normalizer_id:"ncit:C2926"})
RETURN s
```

and 

```cql
MATCH (s) -[:HAS_VARIANT] -> (cv:CategoricalVariation)
MATCH (cv) -[:HAS_DEFINING_CONTEXT|HAS_MEMBERS] -> (v:Variation {id:"ga4gh:VA._8jTS8nAvWwPZGOadQuD1o-tbbTQ5g3H"})
MATCH (s) -[:HAS_TUMOR_TYPE] -> (c:Condition {disease_normalizer_id:"ncit:C2926"})
MATCH (s1:Study) -[:HAS_THERAPEUTIC] ->(tp:TherapeuticAgent {therapy_normalizer_id:"ncit:C2201"})
RETURN s1 as s
UNION
MATCH (s2:Study) -[:HAS_THERAPEUTIC]-> () -[:HAS_SUBSTITUTES|HAS_COMPONENTS] ->(ta:TherapeuticAgent {therapy_normalizer_id:"ncit:C2201"})
RETURN s2 as s
```

Assuming we want the intersection (incorporate all queried terms) and not union, then the results of the first query should be a superset of the results of the second query, but instead, they return entirely different studies from each other.

**Comment by korikuzma** [comment]
@jsstevenson good catch! 

I think this might fix it? Used a therapy normalizer ID from the first query result

```cypher
MATCH (s:Study)
MATCH (s) -[:HAS_VARIANT] -> (cv:CategoricalVariation)
MATCH (cv) -[:HAS_DEFINING_CONTEXT|HAS_MEMBERS] -> (v:Variation {id: "ga4gh:VA._8jTS8nAvWwPZGOadQuD1o-tbbTQ5g3H"})
MATCH (s) -[:HAS_TUMOR_TYPE] -> (c:Condition {disease_normalizer_id: "ncit:C2926"})
OPTIONAL MATCH (s) -[:HAS_THERAPEUTIC] -> (tp:TherapeuticAgent {therapy_normalizer_id: "ncit:C104732"})
OPTIONAL MATCH (s) -[:HAS_THERAPEUTIC] -> () -[:HAS_SUBSTITUTES|HAS_COMPONENTS] -> (ta:TherapeuticAgent {therapy_normalizer_id: "ncit:C104732"})
WITH s, tp, ta
WHERE tp IS NOT NULL OR ta IS NOT NULL
RETURN DISTINCT s
```

**Comment by korikuzma** [comment]
Probably also a good place to add a test for this!

**Comment by jsstevenson** [comment]
> Pushed changes to branch issue-360. Going to let it sit and look at it on Monday to see if it actually makes sense. Not sure why I had written/pushed the original query because it obviously doesn't do what it's supposed to do.

The first time I read it, I assumed it worked like a SQL subquery. I think there's a way you can do something like that using parentheses but I'm not totally sure.
