### ISSUE TITLE
Normalizers fail silently

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#362]
Currently, the normalizer methods catch _all_ errors and log them as warnings. It's pretty easy to miss the presence of critical errors -- I really don't think we should be doing such broad try/catch blocks, and we definitely should be logging stuff like this above "warning"

**Comment by korikuzma** [comment]
I think a general issue about fixing logging levels should be made in our repos. I’ve definitely been guilty of inconsistencies

**Comment by korikuzma** [comment]
I’m not sure if an issue has been made about credentials expiring in normalizers. I think for this exception type, we should exit and raise an exception

**Comment by jsstevenson** [comment]
> I’m not sure if an issue has been made about credentials expiring in normalizers. I think for this exception type, we should exit and raise an exception

Yeah, @korikuzma, this is where I first noticed it -- it's especially troublesome when doing a big transform because it still tries for every entity type, every time, even though the normalizer services are unavailable, and then when you're done you've spent ten minutes to produce no records.
