### ISSUE TITLE
Revise "Study" node type to "Statement"

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#395]
We should update the following node properties in the MetaKB model for greater consistency with VA-Spec:
`Study` -> `Statement`
`VariantTherapeuticResponseStudy` -> `VariantTherapeuticResponseStudyStatement`

**Comment by korikuzma** [comment]
> VariantTherapeuticResponseStudy -> VariantTherapeuticResponseStudyStatement

This exists in the updated models (just haven't pushed my branch).

So just to confirm, for `StudyStatement` we would have the neo4j node be `Statement` and not `StudyStatement`?

**Comment by ahwagner** [comment]
From what I saw of Matt's slides today, it looks like nodes can have multiple type properties? If so, can we put _both_ `Statement` and `StudyStatement` property tags?

**Comment by korikuzma** [comment]
@ahwagner yes

**Comment by ahwagner** [comment]
@korikuzma do it

**Comment by korikuzma** [comment]
🫡

**Comment by korikuzma** [comment]
Going to do this in #388
