### ISSUE TITLE
Establish logging protocol and consistency

### ISSUE THREAD

**Issue by jsstevenson** [cancervariants/metakb#48]
We currently are using Python's built-in [`logging` module](https://docs.python.org/3.8/library/logging.html) in the harvesters to provide information about runtime events. The first question to resolve is whether this is our preferred library (or at least a tentatively acceptable one). Assuming it is, `logging` provides 5 levels of information, and the logging module can be configured to record events up to a certain level (e.g. we may write code to log something at level DEBUG during development, but the production application can be configured to only record events up to WARNING or INFO). [From the official docs](https://docs.python.org/3/howto/logging.html#when-to-use-logging): 

> DEBUG: Detailed information, typically of interest only when diagnosing problems.
> INFO: Confirmation that things are working as expected.
> WARNING: An indication that something unexpected happened, or indicative of some problem in the near future (e.g. ‘disk space low’). The software is still working as expected.
> ERROR: Due to a more serious problem, the software has not been able to perform some function.
> CRITICAL: A serious error, indicating that the program itself may be unable to continue running.

In the normalizers, we've been using INFO to signify phases of computation (like the beginning of an individual source load method) and to mark the beginning/end of long computations (like a download method), and we've used ERROR to note when an expected value is missing (like a reference lookup fails unexpectedly). If an Exception is unhandled and thrown, that will also get caught by logging, but CRITICAL can be used to provide additional context where helpful.

Broadly, I'm not attached to any specific logging method or pattern, but I think we'll save ourselves some future headaches if we can lock some practices down now.

**Comment by korikuzma** [comment]
I think using the built-in logging module is fine right now. I agree that we should only be using DEBUG during development. We should definitely be consistent with what we log. I don't think we are being consistent with the normalizers. Do we ever want logs to display on the terminal _and_ log file?

**Comment by jsstevenson** [comment]
calling this closed as of #346  but we should continue to add better logging where appropriate
