### ISSUE TITLE
Reallocate package-wide deps to requirements.txt

### ISSUE THREAD

**Issue by ahwagner** [cancervariants/metakb#50]
Currently, we are putting all new package requirements in `requirements-dev.txt`.

Any requirements that are needed for normal use (harvesting, normalizing, UI, etc.) should go in `requirements.txt`. Other requirements needed for development only (e.g. testing, debugging, analysis) should go in `requirements-dev.txt`.

We should review what packages are installed in each requirements file and redistribute accordingly.

**Comment by MayLiu27** [comment]
The reallocate changes are made in issue31-MOA branch, all normal use packages are in `requirements.txt`, for dev and test purpose, packages are in 'requirements-dev.txt'

**Comment by korikuzma** [comment]
> The reallocate changes are made in issue31-MOA branch, all normal use packages are in `requirements.txt`, for dev and test purpose, packages are in 'requirements-dev.txt'

Looks good to me!
