### ISSUE TITLE
Search by descriptor IDs in search endpoint

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#80]
THe `search` endpoint does not return a match for `api/v2/search?variation=civic:vid33`. We should allow searches by descriptor IDs in `search`.

**Comment by ahwagner** [comment]
While working towards this, consider adding support for id-based variant normalization directly from the variation normalizer package.

**Comment by korikuzma** [comment]
Closed in https://github.com/cancervariants/metakb/pull/94
