### ISSUE TITLE
DB handling proposition / document index

### ISSUE THREAD

**Issue by korikuzma** [cancervariants/metakb#84]
As new statements get added, proposition / document id's will change since we just increment in the transform methods. We should check if the proposition / document already exists in the database and if it does, use that ID. Otherwise, we should find the max ID and use that as the initial value rather than 1.

**Comment by korikuzma** [comment]
Maybe do something like this and then keep incrementing?
```
MATCH (n)
RETURN n
ORDER BY n.id DESC
LIMIT 1
```

**Comment by jsstevenson** [comment]
Resolved in #142
